<#
.SYNOPSIS
    Builds AGENTS.md from enabled instruction modules.

.DESCRIPTION
    This script generates a single AGENTS.md file by:
    1. Reading the aim.json configuration
    2. Collecting content from enabled modules
    3. Fetching cached fallback modules if applicable
    4. Composing everything into a single AGENTS.md file

.PARAMETER TargetPath
    The path to the target repository. Defaults to parent directory of .aim folder.

.EXAMPLE
    .\build-agents-md.ps1
    Builds AGENTS.md in the parent directory.

.EXAMPLE
    .\build-agents-md.ps1 -TargetPath "C:\Projects\MyRepo"
    Builds AGENTS.md in the specified directory.
#>
[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [string]$TargetPath
)

$ErrorActionPreference = 'Stop'

# Determine paths
$ScriptRoot = $PSScriptRoot
$AimRoot = Split-Path -Parent $ScriptRoot

if ([string]::IsNullOrEmpty($TargetPath)) {
    $TargetPath = Split-Path -Parent $AimRoot
}

$ConfigFile = Join-Path $TargetPath 'aim.json'
$AgentsFile = Join-Path $TargetPath 'AGENTS.md'
$InstructionsPath = Join-Path $AimRoot 'instructions'
$CachePath = Join-Path $TargetPath '.aim-cache'

# Check for aim.json
if (-not (Test-Path $ConfigFile)) {
    Write-Error "aim.json not found at $ConfigFile. Run deploy.ps1 first."
    exit 1
}

# Load configuration
$Config = Get-Content $ConfigFile -Raw | ConvertFrom-Json -AsHashtable

# Get AIM version from CHANGELOG or default
$Version = '0.1.0'
$ChangelogPath = Join-Path $AimRoot 'CHANGELOG.md'
if (Test-Path $ChangelogPath) {
    $ChangelogContent = Get-Content $ChangelogPath -Raw
    if ($ChangelogContent -match '\[(\d+\.\d+\.\d+)\]') {
        $Version = $Matches[1]
    }
}

# Collect enabled modules
$EnabledModules = @()
foreach ($moduleName in $Config.modules.Keys | Sort-Object) {
    $moduleValue = $Config.modules[$moduleName]
    if ($moduleValue -eq $true -or $moduleValue -eq 'awesome-copilot') {
        $EnabledModules += @{
            Name = $moduleName
            Source = if ($moduleValue -eq 'awesome-copilot') { 'awesome-copilot' } else { 'local' }
        }
    }
}

if ($EnabledModules.Count -eq 0) {
    Write-Warning "No modules enabled in aim.json"
}

# Start building AGENTS.md content
$Content = @()
$Content += "# AI Agent Instructions"
$Content += ""
$Content += "> Auto-generated by [AIM](https://github.com/tablackburn/ai-agent-instruction-modules) v$Version"
$Content += "> Last sync: $(Get-Date -Format 'yyyy-MM-dd')"
$Content += "> Enabled modules: $($EnabledModules.Count)"
$Content += ""

# Build table of contents
$Content += "## Table of Contents"
$Content += ""
foreach ($module in $EnabledModules) {
    $DisplayName = ($module.Name -split '/')[-1]
    $DisplayName = (Get-Culture).TextInfo.ToTitleCase(($DisplayName -replace '-', ' '))
    $Anchor = $DisplayName.ToLower() -replace ' ', '-'
    $Content += "- [$DisplayName](#$Anchor)"
}
$Content += ""

# Add each module's content
foreach ($module in $EnabledModules) {
    $ModuleName = $module.Name
    $ModuleSource = $module.Source

    $DisplayName = ($ModuleName -split '/')[-1]
    $DisplayName = (Get-Culture).TextInfo.ToTitleCase(($DisplayName -replace '-', ' '))

    $Content += "---"
    $Content += ""
    $Content += "## $DisplayName"
    $Content += ""
    $Content += "<!-- BEGIN: $ModuleName -->"
    $Content += ""

    # Get module content
    $ModuleContent = $null

    if ($ModuleSource -eq 'local') {
        $ModulePath = Join-Path $InstructionsPath "$ModuleName.md"
        if (Test-Path $ModulePath) {
            $ModuleContent = Get-Content $ModulePath -Raw

            # Strip YAML frontmatter if present
            if ($ModuleContent -match '^---\r?\n[\s\S]*?\r?\n---\r?\n(.*)$') {
                $ModuleContent = $Matches[1]
            }

            # Remove the first H1 header if it matches the module name
            $ModuleContent = $ModuleContent -replace "^#\s+$([regex]::Escape($DisplayName))\s*\r?\n", ''
        }
        else {
            $ModuleContent = "*Module file not found: $ModulePath*"
            Write-Warning "Module not found: $ModulePath"
        }
    }
    elseif ($ModuleSource -eq 'awesome-copilot') {
        $CacheFile = Join-Path $CachePath "$($ModuleName -replace '/', '_').md"
        if (Test-Path $CacheFile) {
            $ModuleContent = Get-Content $CacheFile -Raw

            # Strip YAML frontmatter if present
            if ($ModuleContent -match '^---\r?\n[\s\S]*?\r?\n---\r?\n(.*)$') {
                $ModuleContent = $Matches[1]
            }
        }
        else {
            $ModuleContent = "*Fallback module not cached. Run sync.ps1 to fetch.*"
            Write-Warning "Fallback module not cached: $ModuleName. Run sync.ps1 to fetch."
        }
    }

    $Content += $ModuleContent.Trim()
    $Content += ""
    $Content += "<!-- END: $ModuleName -->"
    $Content += ""
}

# Add custom instructions if specified
if ($Config.customInstructionsPath) {
    $CustomPath = Join-Path $TargetPath $Config.customInstructionsPath
    if (Test-Path $CustomPath) {
        $Content += "---"
        $Content += ""
        $Content += "## Custom Instructions"
        $Content += ""
        $Content += "<!-- BEGIN: custom -->"
        $Content += ""
        $CustomContent = Get-Content $CustomPath -Raw
        $Content += $CustomContent.Trim()
        $Content += ""
        $Content += "<!-- END: custom -->"
        $Content += ""
    }
}

# Write AGENTS.md
$FinalContent = $Content -join "`n"
Set-Content -Path $AgentsFile -Value $FinalContent -Encoding UTF8 -NoNewline

Write-Host "Generated: $AgentsFile" -ForegroundColor Green
Write-Host "  Modules: $($EnabledModules.Count)"
